const ACTIONBAR = {
  // ACTION BAR BONUSES
  PRIZE_BAG: "PRIZE_BAG",
  STOP_LOSS: "STOP_LOSS",
  DOUBLE_EDGED_TRADES: "DOUBLE_EDGED_TRADES",
  HEALTH_PUMPS: "HEALTH_PUMPS",
  TRADELIXER: "TRADELIXER",
  TRADE_RECOVERY: "TRADE_RECOVERY",
  ACTION_BAR: "ACTION_BAR",
  XP_STACK: "XP_STACK",
  PEEK_METER: "PEEK_METER",
  TRADE_DELAY: "TRADE_DELAY",

  // MULTIPLIER BONUSES
  PEEK_METER_MULTIPLIER: "PEEK_METER_MULTIPLIER",
  PEEK_METER_REFILL: "PEEK_METER_REFILL",
  TRADE_DELAY_MULTIPLIER: "TRADE_DELAY_MULTIPLIER",
  TRADE_DELAY_REFILL: "TRADE_DELAY_REFILL",
  PROFIT: "PROFIT",
  ACTION_BAR_MULTIPLIER: "ACTION_BAR_MULTIPLIER",
  TRADELIXER_DISCOUNT: "TRADELIXER_DISCOUNT",
};

const ACTIONBAR_CATEGORIES = [
  // ACTION BAR BONUSES
  {
    key: ACTIONBAR.PRIZE_BAG,
    name: "Prize Bag",
    icon: "🎁",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.STOP_LOSS,
    name: "Stop Loss",
    icon: "🛡️",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.DOUBLE_EDGED_TRADES,
    name: "Double Edged Trades",
    icon: "⚔️",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.HEALTH_PUMPS,
    name: "Health Pumps",
    icon: "❤️",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.TRADELIXER,
    name: "TradeliXer",
    icon: "🧪",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.TRADE_RECOVERY,
    name: "Trade Recovery",
    icon: "♻️",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.ACTION_BAR,
    name: "Action Bar",
    icon: "⚡",
    type: "actionbar",
  },
  { key: ACTIONBAR.XP_STACK, name: "XP Stack", icon: "⭐", type: "actionbar" },
  {
    key: ACTIONBAR.PEEK_METER,
    name: "Peek Meter",
    icon: "👁️",
    type: "actionbar",
  },
  {
    key: ACTIONBAR.TRADE_DELAY,
    name: "Trade Delay",
    icon: "⏱️",
    type: "actionbar",
  },

  // MULTIPLIER BONUSES
  {
    key: ACTIONBAR.PEEK_METER_MULTIPLIER,
    name: "Peek Meter Multiplier",
    icon: "📈",
    type: "multiplier",
  },
  {
    key: ACTIONBAR.PEEK_METER_REFILL,
    name: "Peek Meter Refill",
    icon: "🔄",
    type: "multiplier",
  },
  {
    key: ACTIONBAR.TRADE_DELAY_MULTIPLIER,
    name: "Trade Delay Multiplier",
    icon: "⏰",
    type: "multiplier",
  },
  {
    key: ACTIONBAR.TRADE_DELAY_REFILL,
    name: "Trade Delay Refill",
    icon: "🔄",
    type: "multiplier",
  },
  {
    key: ACTIONBAR.PROFIT,
    name: "Profit Bonus",
    icon: "💰",
    type: "multiplier",
  },
  {
    key: ACTIONBAR.ACTION_BAR_MULTIPLIER,
    name: "Action Bar Multiplier",
    icon: "⚡",
    type: "multiplier",
  },
  {
    key: ACTIONBAR.TRADELIXER_DISCOUNT,
    name: "TradeliXer Discount",
    icon: "💸",
    type: "multiplier",
  },
];

const MULTIPLIER_CATEGORIES = {
  [ACTIONBAR.PEEK_METER_MULTIPLIER]: [
    {
      name: "PM 1",
      key: "MULT_PM_1",
      value: 5,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 2",
      key: "MULT_PM_2",
      value: 10,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 3",
      key: "MULT_PM_3",
      value: 15,
      max: 80,
      multiplier_type: "x1",
    },
    { name: "PM 4", key: "PM_4", value: 20, max: 80, multiplier_type: "x1" },
    {
      name: "PM 5",
      key: "MULT_PM_5",
      value: 25,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 6",
      key: "MULT_PM_6",
      value: 30,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 7",
      key: "MULT_PM_7",
      value: 35,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 8",
      key: "MULT_PM_8",
      value: 40,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 9",
      key: "MULT_PM_9",
      value: 45,
      max: 80,
      multiplier_type: "x1",
    },
    {
      name: "PM 10",
      key: "MULT_PM_10",
      value: 50,
      max: 80,
      multiplier_type: "x1",
    },
  ],
  [ACTIONBAR.PEEK_METER_REFILL]: [
    {
      name: "RFLPM 1",
      key: "MULT_RFLPM_1",
      value: 4,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 2",
      key: "MULT_RFLPM_2",
      value: 8,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 3",
      key: "MULT_RFLPM_3",
      value: 12,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 4",
      key: "MULT_RFLPM_4",
      value: 16,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 5",
      key: "MULT_RFLPM_5",
      value: 20,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 6",
      key: "MULT_RFLPM_6",
      value: 24,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 7",
      key: "MULT_RFLPM_7",
      value: 28,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 8",
      key: "MULT_RFLPM_8",
      value: 32,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 9",
      key: "MULT_RFLPM_9",
      value: 36,
      max: 70,
      multiplier_type: "x2",
    },
    {
      name: "RFLPM 10",
      key: "MULT_RFLPM_10",
      value: 40,
      max: 70,
      multiplier_type: "x2",
    },
  ],
  [ACTIONBAR.TRADE_DELAY_MULTIPLIER]: [
    {
      name: "TD 1",
      key: "MULT_TD_1",
      value: 3,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 2",
      key: "MULT_TD_2",
      value: 6,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 3",
      key: "MULT_TD_3",
      value: 9,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 4",
      key: "MULT_TD_4",
      value: 12,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 5",
      key: "MULT_TD_5",
      value: 15,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 6",
      key: "MULT_TD_6",
      value: 18,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 7",
      key: "MULT_TD_7",
      value: 21,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 8",
      key: "MULT_TD_8",
      value: 24,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 9",
      key: "MULT_TD_9",
      value: 27,
      max: 45,
      multiplier_type: "x3",
    },
    {
      name: "TD 10",
      key: "MULT_TD_10",
      value: 30,
      max: 45,
      multiplier_type: "x3",
    },
  ],
  [ACTIONBAR.TRADE_DELAY_REFILL]: [
    {
      name: "RFLTD 1",
      key: "MULT_RFLTD_1",
      value: 2.5,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 2",
      key: "MULT_RFLTD_2",
      value: 5,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 3",
      key: "MULT_RFLTD_3",
      value: 7.5,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 4",
      key: "MULT_RFLTD_4",
      value: 10,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 5",
      key: "MULT_RFLTD_5",
      value: 12.5,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 6",
      key: "MULT_RFLTD_6",
      value: 15,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 7",
      key: "MULT_RFLTD_7",
      value: 17.5,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 8",
      key: "MULT_RFLTD_8",
      value: 20,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 9",
      key: "MULT_RFLTD_9",
      value: 22.5,
      max: 40,
      multiplier_type: "x4",
    },
    {
      name: "RFLTD 10",
      key: "MULT_RFLTD_10",
      value: 25,
      max: 40,
      multiplier_type: "x4",
    },
  ],
  [ACTIONBAR.PROFIT]: [
    {
      name: "+$ 1",
      key: "MULT_PROFIT_1",
      value: 2,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 2",
      key: "MULT_PROFIT_2",
      value: 4,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 3",
      key: "MULT_PROFIT_3",
      value: 6,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 4",
      key: "MULT_PROFIT_4",
      value: 8,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 5",
      key: "MULT_PROFIT_5",
      value: 10,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 6",
      key: "MULT_PROFIT_6",
      value: 12,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 7",
      key: "MULT_PROFIT_7",
      value: 14,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 8",
      key: "MULT_PROFIT_8",
      value: 16,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 9",
      key: "MULT_PROFIT_9",
      value: 18,
      max: 100,
      multiplier_type: "x5",
    },
    {
      name: "+$ 10",
      key: "MULT_PROFIT_10",
      value: 20,
      max: 100,
      multiplier_type: "x5",
    },
  ],
  [ACTIONBAR.ACTION_BAR_MULTIPLIER]: [
    {
      name: "+AB 1",
      key: "MULT_AB_1",
      value: 10,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 2",
      key: "MULT_AB_2",
      value: 20,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 3",
      key: "MULT_AB_3",
      value: 30,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 4",
      key: "MULT_AB_4",
      value: 40,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 5",
      key: "MULT_AB_5",
      value: 50,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 6",
      key: "MULT_AB_6",
      value: 60,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 7",
      key: "MULT_AB_7",
      value: 70,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 8",
      key: "MULT_AB_8",
      value: 80,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 9",
      key: "MULT_AB_9",
      value: 90,
      max: 100,
      multiplier_type: "x6",
    },
    {
      name: "+AB 10",
      key: "MULT_AB_10",
      value: 100,
      max: 100,
      multiplier_type: "x6",
    },
  ],
  [ACTIONBAR.TRADELIXER_DISCOUNT]: [
    {
      name: "-TE 1",
      key: "MULT_TE_DISC_1",
      value: 5,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 2",
      key: "MULT_TE_DISC_2",
      value: 10,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 3",
      key: "MULT_TE_DISC_3",
      value: 15,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 4",
      key: "MULT_TE_DISC_4",
      value: 20,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 5",
      key: "MULT_TE_DISC_5",
      value: 25,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 6",
      key: "MULT_TE_DISC_6",
      value: 30,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 7",
      key: "MULT_TE_DISC_7",
      value: 35,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 8",
      key: "MULT_TE_DISC_8",
      value: 40,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 9",
      key: "MULT_TE_DISC_9",
      value: 45,
      max: 50,
      multiplier_type: "x7",
    },
    {
      name: "-TE 10",
      key: "MULT_TE_DISC_10",
      value: 50,
      max: 50,
      multiplier_type: "x7",
    },
  ],
};

module.exports = {
  ACTIONBAR,
  ACTIONBAR_CATEGORIES,
  MULTIPLIER_CATEGORIES,
};
